// `.env.ts` is generated by the `npm run env` command
// `npm run env` exposes environment variables as JSON for any usage you might
// want, like displaying the version or getting extra config from your CI bot, etc.
// This is useful for granularity you might need beyond just the environment.
// Note that as usual, any environment variables you expose through it will end up in your
// bundle, and you should not use it for any sensitive information like passwords or keys.
//import { env } from './.env';

export const environment = {
  firebase: {
    projectId: 'ejercicio-emt-be0b5',
    appId: '1:953976298785:web:41f434204cec327bcbf260',
    databaseURL: 'https://ejercicio-emt-be0b5-default-rtdb.firebaseio.com',
    storageBucket: 'ejercicio-emt-be0b5.appspot.com',
    apiKey: 'AIzaSyBjURnM1AIWt5UO374eJRoLEpXeT-orFyI',
    authDomain: 'ejercicio-emt-be0b5.firebaseapp.com',
    messagingSenderId: '953976298785',
  },
  production: true,
  version: '1.0.1',
  serverUrl: 'https://api.chucknorris.io',
  defaultLanguage: 'en-US',
  supportedLanguages: ['en-US', 'es-ES']
};
